In [106]:
import pandas as pd
import numpy as np

In [107]:
df=pd.read_excel('Churn_Unclean_Project.xlsx')

In [108]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [109]:
df.isnull().sum()

Customer_ID               0
Customer_Name             9
Gender                    6
Age                       6
State                    11
City                      3
Tenure_Months             8
Subscription_Type        12
Monthly_Charges          13
Total_Charges             9
Contract_Type             4
Payment_Method           16
Internet_Service          7
Tech_Support             12
Senior_Citizen            8
Dependents                3
Churn                     4
Last_Interaction_Date     3
dtype: int64

In [110]:
df.duplicated().sum()

np.int64(7)

In [111]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            542 non-null    str
 1   Customer_Name          533 non-null    str
 2   Gender                 536 non-null    str
 3   Age                    536 non-null    float64
 4   State                  531 non-null    str
 5   City                   539 non-null    str
 6   Tenure_Months          534 non-null    float64
 7   Subscription_Type      530 non-null    str
 8   Monthly_Charges        529 non-null    float64
 9   Total_Charges          533 non-null    float64
 10  Contract_Type          538 non-null    str
 11  Payment_Method         526 non-null    str
 12  Internet_Service       535 non-null    str
 13  Tech_Support           530 non-null    str
 14  Senior_Citizen         534 non-null    str
 15  Dependents             539 non-null    str
 16  Churn                  538 non-null    str
 17  Last_Interaction_Date  539 non-null    str
dtypes: float64(4), str(14)
memory usage: 120.0 KB

In [112]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

In [113]:
df.shape

(542, 18)

In [114]:
df.drop_duplicates(inplace=True)

In [115]:
df.shape

(535, 18)

In [116]:
df.replace(['N/A','NULL',' ',''],np.nan,inplace=True)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-to-Month,UPI,DSL,Yes,No,No,No,26-12-2025
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,BASIC,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
541,C5009,Rahul Singh,Male,25.0,UP,Kanpur,30.0,Basic,1341.52,NaN,Month-to-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025

In [117]:
df.apply(lambda x: x.str.strip() if x.dtype=='str' else x)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-to-Month,UPI,DSL,Yes,No,No,No,26-12-2025
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,BASIC,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
541,C5009,Rahul Singh,Male,25.0,UP,Kanpur,30.0,Basic,1341.52,NaN,Month-to-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025

In [118]:
df['Customer_Name']=df['Customer_Name'].str.title()
df['State']=df['State'].str.title()
df['City']=df['City'].str.title()
df['Subscription_Type']=df['Subscription_Type'].str.title()
df['Contract_Type']=df['Contract_Type'].str.title()

In [119]:
df['Subscription_Type'].value_counts()

Subscription_Type
Premium      180
Basic        169
Standard     168
Premium        3
Premium        1
Basic          1
Standard       1
  Basic        1
Name: count, dtype: int64

In [120]:
df['Subscription_Type']=df['Subscription_Type'].str.strip()

In [121]:
df['Subscription_Type'].value_counts()

Subscription_Type
Premium     184
Basic       171
Standard    169
Name: count, dtype: int64

In [122]:
df['Churn'].value_counts()

Churn
No     405
Yes    125
YES      1
yes      1
Name: count, dtype: int64

In [123]:
df['Churn']=df['Churn'].str.title()
df['Gender']=df['Gender'].str.title()

In [124]:
df['Gender'].value_counts()

Gender
Female    270
Male      258
 Male       2
Name: count, dtype: int64

In [125]:
df['Gender']=df['Gender'].str.strip()

In [126]:
df['Gender'].value_counts()

Gender
Female    270
Male      260
Name: count, dtype: int64

In [127]:
df=df[(df['Age']>=18) & (df['Age']<=100)]

In [128]:
df['Age'].max()

np.float64(70.0)

In [129]:
df=df[df['Monthly_Charges']>=0]
df=df[df['Total_Charges']>=0]

In [130]:
df.shape

(492, 18)

In [131]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'State', 'City',
       'Tenure_Months', 'Subscription_Type', 'Monthly_Charges',
       'Total_Charges', 'Contract_Type', 'Payment_Method', 'Internet_Service',
       'Tech_Support', 'Senior_Citizen', 'Dependents', 'Churn',
       'Last_Interaction_Date'],
      dtype='str')

In [132]:
cols=['Age','Tenure_Months','Monthly_Charges','Total_Charges']

for c in cols:
    df[c]=pd.to_numeric(df[c],errors='coerce')

In [133]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,UPI,DSL,Yes,No,No,No,26-12-2025
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025

In [134]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,UPI,DSL,Yes,No,No,No,26-12-2025
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025

In [135]:
df.shape

(492, 18)

In [139]:
df['Last_Interaction_Date'].head(200)

0      12-10-2025
2      20-02-2026
4      02-04-2026
6      26-12-2025
7      14-01-2025
          ...
225    13-05-2026
226    25-01-2026
227    18-03-2025
228    31-08-2025
229    21-11-2025
Name: Last_Interaction_Date, Length: 200, dtype: str

In [140]:
df['Last_Interaction_Date']=pd.to_datetime(df['Last_Interaction_Date'],format='%d-%m-%y',errors='coerce'op

In [141]:
df['Last_Interaction_Date'].isnull().sum()

np.int64(2)

In [142]:
df

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,2025-10-12
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,2026-02-20
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-04-02
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,UPI,DSL,Yes,No,No,No,2025-12-26
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,2025-01-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,C5002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,2026-02-20
536,C5004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-04-02
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,UPI,DSL,Yes,No,No,No,2025-12-26
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,2025-01-14
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,Basic,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,2025-02-28

In [143]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Tech_Support'].fillna('Unknown',inplace=True)
df['Payment_Method'].fillna('Unknown',inplace=True)
df['Monthly_Charges'].fillna(df['Monthly_Charges'].mean(),inplace=True)
    df['Tenure_Months'].fillna(df['Tenure_Months'].mean(),inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_6884\2806347857.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(df['Age'].mean(),inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_6884\2806347857.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Tech_Support'].fillna('Unknown',inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_6884\2806347857.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Payment_Method'].fillna('Unknown',inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_6884\2806347857.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Monthly_Charges'].fillna(df['Monthly_Charges'].mean(),inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_6884\2806347857.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Tenure_Months'].fillna(df['Tenure_Months'].mean(),inplace=True)

0      58.0
2      13.0
4       6.0
6      70.0
7      57.0
       ...
534    13.0
536     6.0
538    70.0
539    57.0
540    63.0
Name: Tenure_Months, Length: 492, dtype: float64

In [145]:
df.shape

(492, 18)

In [146]:
df['Customer_value']=df['Monthly_Charges']*df['Tenure_Months']

In [147]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_value
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,2025-10-12,93627.08
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,2026-02-20,7215.39
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-04-02,1884.12
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,UPI,DSL,Yes,No,No,No,2025-12-26,140618.10
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,2025-01-14,125182.26

In [148]:
df['Monthly_revenue']=df['Monthly_Charges']

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_value,Monthly_revenue
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,2025-10-12,93627.08,1614.26
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,2026-02-20,7215.39,555.03
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-04-02,1884.12,314.02
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,UPI,DSL,Yes,No,No,No,2025-12-26,140618.10,2008.83
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,2025-01-14,125182.26,2196.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,C5002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,2026-02-20,7215.39,555.03
536,C5004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-04-02,1884.12,314.02
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,UPI,DSL,Yes,No,No,No,2025-12-26,140618.10,2008.83
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,2025-01-14,125182.26,2196.18
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,Basic,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,2025-02-28,75600.00,1200.00

In [150]:
df.shape

(492, 20)

In [151]:
df.drop('Monthly_Charges', axis=1, inplace=True)

In [152]:
df

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_value,Monthly_revenue
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,2025-10-12,93627.08,1614.26
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,2026-02-20,7215.39,555.03
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-04-02,1884.12,314.02
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,140376.10,Month-To-Month,UPI,DSL,Yes,No,No,No,2025-12-26,140618.10,2008.83
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,2025-01-14,125182.26,2196.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,C5002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,2026-02-20,7215.39,555.03
536,C5004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-04-02,1884.12,314.02
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,140376.10,Month-To-Month,UPI,DSL,Yes,No,No,No,2025-12-26,140618.10,2008.83
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,2025-01-14,125182.26,2196.18
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,Basic,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,2025-02-28,75600.00,1200.00

In [153]:
bins=[0,12,24,48,72]

label=labels=['0-12 month','12-24 month','24-48 month','48-72 month']
df['Tenure_group']=pd.cut(df['Tenure_Months'],bins=bins,labels=label)

In [154]:
df

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_value,Monthly_revenue,Tenure_group
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,2025-10-12,93627.08,1614.26,48-72 month
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,2026-02-20,7215.39,555.03,12-24 month
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-04-02,1884.12,314.02,0-12 month
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,140376.10,Month-To-Month,UPI,DSL,Yes,No,No,No,2025-12-26,140618.10,2008.83,48-72 month
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,2025-01-14,125182.26,2196.18,48-72 month
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,C5002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,2026-02-20,7215.39,555.03,12-24 month
536,C5004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-04-02,1884.12,314.02,0-12 month
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,140376.10,Month-To-Month,UPI,DSL,Yes,No,No,No,2025-12-26,140618.10,2008.83,48-72 month
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,2025-01-14,125182.26,2196.18,48-72 month
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,Basic,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,2025-02-28,75600.00,1200.00,48-72 month

In [155]:
df['Senior_flag']=np.where(df['Age']>=60,'Senior','Adult')

In [156]:
df['Churn_flag']=df['Churn'].map({'Yes':1,'No':0})

In [157]:
df.info()

<class 'pandas.DataFrame'>
Index: 492 entries, 0 to 540
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            492 non-null    str
 1   Customer_Name          487 non-null    str
 2   Gender                 488 non-null    str
 3   Age                    492 non-null    float64
 4   State                  485 non-null    str
 5   City                   487 non-null    str
 6   Tenure_Months          487 non-null    float64
 7   Subscription_Type      486 non-null    str
 8   Total_Charges          492 non-null    float64
 9   Contract_Type          490 non-null    str
 10  Payment_Method         477 non-null    str
 11  Internet_Service       486 non-null    str
 12  Tech_Support           483 non-null    str
 13  Senior_Citizen         486 non-null    str
 14  Dependents             491 non-null    str
 15  Churn                  490 non-null    str
 16  Last_Interaction_Date  490 non-null    datetime64[us]
 17  Customer_value         487 non-null    float64
 18  Monthly_revenue        492 non-null    float64
 19  Tenure_group           487 non-null    category
 20  Senior_flag            492 non-null    str
 21  Churn_flag             490 non-null    float64
dtypes: category(1), datetime64[us](1), float64(6), str(14)
memory usage: 122.5 KB

In [158]:
df['Last_Interaction_Date'].fillna(df['Last_Interaction_Date'].median(),inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_6884\1293760172.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Last_Interaction_Date'].fillna(df['Last_Interaction_Date'].median(),inplace=True)

0     2025-10-12
2     2026-02-20
4     2026-04-02
6     2025-12-26
7     2025-01-14
         ...
534   2026-02-20
536   2026-04-02
538   2025-12-26
539   2025-01-14
540   2025-02-28
Name: Last_Interaction_Date, Length: 492, dtype: datetime64[us]

In [159]:
df.shape

(492, 22)

In [160]:
df.to_csv('Clean_churn_data.csv',index=False)

In [161]:
from sqlalchemy import create_engine

engine=create_engine("mysql+pymysql://root:Manipal#456@localhost/churn_db")

In [162]:
df.to_sql(
name='cust_churn',
con=engine,
if_exists='replace',
index=False)

492